#!/usr/bin/env bash

sudo -v

brew bundle --file=~/Dotfiles/Brewfile

bash ~/Dotfiles/.macos

ln -sf ~/Dotfiles/.gitconfig ~/.gitconfig
ln -sf ~/Dotfiles/config.fish ~/.config/fish/config.fish
ln -sf ~/Dotfiles/bundler-config ~/.bundle/config
ln -sf ~/Dotfiles/atom-config.cson ~/.atom/config.cson
sudo ln -sf ~/Dotfiles/hosts /etc/hosts

if [[ $(dscl . -read /Users/`id -un`/ UserShell) =~ .*fish$ ]];
then
  echo "Shell already set to fish"
else
  echo `which fish` | sudo tee -a /etc/shells
  chsh -s `which fish`
fi
